server.port=8080
spring.profiles.active=postgres

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# JWT
jwt.secret=YourSuperSecretKeyForJWTThatIsAtLeast256BitsLongChangeThisInProduction1234567890
jwt.expiration-ms=86400000

# Storage
storage.local.upload-dir=uploads
storage.local.hls-dir=hls

# FFmpeg
ffmpeg.path=ffmpeg
ffmpeg.ffprobe.path=ffprobe

# Stripe
stripe.secret-key=
stripe.webhook-secret=
stripe.price-id=price_monthly_premium

# App
app.base-url=http://localhost:8080

spring.servlet.multipart.max-file-size=2048MB
spring.servlet.multipart.max-request-size=2048MB
spring.servlet.multipart.enabled=true
